### ISSUE TITLE
DE_TOOLKIT_HOME must be defined

### ISSUE THREAD

**Issue by petenicholls** [IBMStreams/streamsx.document#2]
The code throws an exception if DE_TOOLKIT_HOME is not set.  The spldoc implies this is optional if the config folder is fully specified.  

Looking at the code an exception is throw in DocumentSourceUtils.getDefaultConfigFolderPath() if the environment variable is not defined.

This should be updated to make this work without having to specify the environment variable.

**Comment by apyasic** [comment]
Fixed in 1.0.3
